### ISSUE TITLE
Absolute minimum requirement for running?

### ISSUE THREAD

**Issue by MostHated** [dotnet-script/dotnet-script#681]
Hey there,
    I know that the .Net SDK is listed as a prereq, but I was wondering if the full fat sdk is necessary for running dotnet-script? I would definitely like utilize some scripts in my work environment. I was lucky to get Pwsh 7.x, but getting approval from my security team for the full .Net SDK for only script functionality is going to be tough. If I can whittle it down to only minimum necessary components to run the scripts, I might actually have a chance. 

I was going to begin looking into it / experimenting, but figured it was worth posing the question, just in case there was any insight that could help point me in the right direction.

Thanks,
-MH

**Comment by filipw** [comment]
Yes the full SDK is needed because dotnet-script effectively runs the normal `dotnet restore` to assemble a manifest of compile-time and runtime dependencies.

If you want an SDK-free experience, you can precompile a script to [an executable](https://github.com/filipw/dotnet-script#creating-dlls-or-exes-from-a-csx-file) on a machine with an SDK installed, at which point it can be deployed and run without any extra dependencies, but you won't be able to modify it.
