### ISSUE TITLE
Change target framework from `net7.0` to `net472`

### ISSUE THREAD

**Issue by amine-aboufirass** [dotnet-script/dotnet-script#729]
When I run `dotnet script --info` here's the output I get:

```
Version             : 1.4.0
Install location    : C:\Users\aa\.dotnet\tools\.store\dotnet-script\1.4.0\dotnet-script\1.4.0\tools\net7.0\any
Target framework    : net7.0
.NET Core version   : 7.0.5
Platform identifier : win
Runtime identifier  : win10-x64
```

I would like to run my script as using `net472` instead of `net472` as the target framework. Is this possible?

**Comment by filipw** [comment]
it is not possible to run the script as `net472`. .NET Framework is not supported by the command line runner by design.

[Dotnet.Script.Core](https://www.nuget.org/packages/Dotnet.Script.Core), which is effectively the heart of donet-script is cross compiled for .NET Standard 2.0 and can be used from a .NET Framework app (or host) so it could potentially be used to manually orchestrate the script running. [These tests](https://github.com/dotnet-script/dotnet-script/blob/master/src/Dotnet.Script.Shared.Tests/InteractiveRunnerTestsBase.cs) are executed for `net472` too and can provide some reference point.
