### ISSUE TITLE
syntax highlighting + intellisense not working for project created using `dotnet script init`

### ISSUE THREAD

**Issue by amine-aboufirass** [dotnet-script/dotnet-script#737]
I tried creating a scripting project using `dotnet script init` and then opened it on VS Code. When I open `main.csx`, syntax highlighting appears for a brief moment and then disappears as soon as the following line appears in the Output window:

```
[Info  - 4:50:53 PM] [Program]Language server initialized
```

Initially I thought this might be an Omnisharp [issue](https://github.com/dotnet/vscode-csharp/issues/6411), but the syntax highlighting + intellisense seem to work just fine on a conventional console application. 

Should I expect syntax highlighting + intellisense to work with `dotnet-script`? If so what might be going on here?

**Comment by seesharper** [comment]
Hi. This is probably because you have the C# Dev Kit installed and hence OmniSharp is not used here.

Step 1. Make sure that the C# Dev Kit extension is uninstalled
Step 2. Make sure that "Use Omnisharp" is ticket in the settings. 

<img width="755" alt="image" src="https://github.com/dotnet-script/dotnet-script/assets/1034073/4627203f-b89f-4e74-8f6e-67bb72d62ed6">

Microsoft basically killed OmniSharp (and dotnet-script language services) when they decided to write their  backend.
It did not land well in the OSS community. Most of the discussion can be found here
https://github.com/dotnet/vscode-csharp/issues/5276

**Comment by seesharper** [comment]
I have not fully understood this myself. Although Microsoft is developing their own closed source LSP-based host to provide language services, there is still people from Microsoft working with OmniSharp-Roslyn which we now need to opt in to use. 
There is also an effort to bring LSP to Omnisharp through this project https://github.com/OmniSharp/csharp-language-server-protocol. This is also mostly driven by Joey Robichaud which is employed at Microsoft. 
So to me it seems that maybe they are keeping Omnisharp alive just in case this new thing goes south. I don't know 😃

**Comment by amis92** [comment]
It's supposedly on their table, let's see if they can get the integration in. I was interested as well and found the issue on their open-source repo for that: https://github.com/dotnet/vscode-csharp/issues/5722
